### ISSUE TITLE
Pay

### ISSUE THREAD

**Issue by frqher** [0x178F/shopier-api#1]
Kendi dökümanlarına baktığımda bir ödeme sayfası oluşturma gibi özellik göremedim, youtubede araştırdım ve php için buldum fakat aynısını nodejs için bulamadım, sizin kütüphanenizi deneme fısatım olmadı. Tam olarak resimdeki gibi mi?
[https://i.imgur.com/8soFYVe.png](url)

**Comment by 0x178F** [comment]
@frqher Merhaba, evet aynı şekilde.

**Comment by frqher** [comment]
Paylaşım için teşekkür ederim
